#!/bin/ksh
#
#====================================================================
#
# script: add_yy   
# Version: 20001106
#
# given an initial date (date0=ccyymmddhh) and a number of years (ny)
# this function returns the final date 
# new_date = date0 + ny
#
# usage: add_yy date0 ny
#
#====================================================================
#
if (( $# != 2 )); then
   echo ' Usage: add_yy date0 n_years '
   exit 1
fi
date0=$1
ny=$2
typeset -Z4  yy
yy=`echo $date0 | cut -c1-4`
mm=`echo $date0 | cut -c5-6`
dd=`echo $date0 | cut -c7-8`
hh=`echo $date0 | cut -c9-10`

(( new_date = date0 ))

if (( ny > 0 )) ;then
   i=1
   while (( i <= ny  ))
   do
     (( yy = yy + 1 ))
     new_date=$yy$mm$dd$hh
     (( i = i + 1 ))
   done
fi
#
if (( ny < 0 )) ;then
   i=0
   while (( i > ny )) 
   do
     (( yy = yy - 1 ))
     new_date=$yy$mm$dd$hh
     (( i = i - 1 ))
   done
fi
#
echo $new_date
#
#=== end script add_yy =========
#
