#!/bin/bash

PATH=$PATH:/usr/lib/gmt/bin/
file=/home/vermert/gmt

info=/home/af/Synops/synstat_neu1.dat

if [ -s out.ps ] ; then
 rm out.ps
fi

statken=${1}
grep ${statken} ${info} | awk '{printf("%s test\n",$5);}' > dat1
read ctitle cdum < dat1
echo $ctitle

datinp=/home/vermert/qweci/wp5.1/lmm/${statken}_daily.txt
datout=${statken}_year.ps

yyyb=1973
yyye=2006
yyyy=$yyyb
while [ $yyyy -le $yyye ]
do

yyys=`expr $yyyy + 1`

awk -vyyyy=${yyyy} '{
      if ( substr($1,1,4) == yyyy) printf("%s %11.2f\n",$1,$2);
     }' ${datinp} > datT

awk -vyyyy=${yyyy} '{
      if ( substr($1,1,4) == yyyy) printf("%s %11.2f\n",$1,$3);
     }' ${datinp} > datRR

awk -vyyyy=${yyyy} '{
      if ( substr($1,1,4) == yyyy) printf("%s %11.2f\n",$1,$4);
     }' ${datinp} > datN

awk -vyyyy=${yyyy} '{
      if ( substr($1,1,4) == yyyy) printf("%s %11.2f\n",$1,$5*30.0);
     }' ${datinp} > datEIR

awk -vyyyy=${yyyy} '{
      if ( substr($1,1,4) == yyyy) printf("%s %11.2f\n",$1,$6);
     }' ${datinp} > datHBR

awk -vyyyy=${yyyy} '{
      if ( substr($1,1,4) == yyyy) printf("%s %11.2f\n",$1,$7);
     }' ${datinp} > datPR

ratio=24/15

#############################################

area1=${yyyy}-01-01T00:00:00/${yyys}-01-01T00:00:00/0.0/100.0
area2=${yyyy}-01-01T00:00:00/${yyys}-01-01T00:00:00/0.0/500.0

psbasemap --PLOT_DATE_FORMAT=yyyy-mm --BASEMAP_FRAME_RGB=+black --ANOT_FONT=Helvetica --ANNOT_FONT_SIZE_PRIMARY=14 --ANNOT_OFFSET_SECONDARY=-0.1c --LABEL_FONT=Helvetica-Bold --LABEL_FONT_SIZE=16 --GRID_PEN=0.75p/0/0/0ta --HEADER_FONT_SIZE=20 --HEADER_OFFSET=-0.35c -R${area1} -JX${ratio} -Ba1O:"time [year-month]":/a10g20f1:"R@-d@- [mm]":WS -X3.0 -Y2.0 -K > out.ps
psxy datEIR -R${area1} -m -Wthick,red -JX${ratio} -O -K >> out.ps
psxy datHBR -R${area1} -m -Wthick,royalblue -JX${ratio} -O -K >> out.ps


psbasemap --PLOT_DATE_FORMAT=yyyy-mm --BASEMAP_FRAME_RGB=+green --ANOT_FONT=Helvetica --ANNOT_FONT_SIZE_PRIMARY=14 --ANNOT_OFFSET_SECONDARY=0.1c --LABEL_FONT=Helvetica-Bold --LABEL_FONT_SIZE=14 --GRID_PEN=0.75p/0/0/0ta --HEADER_FONT_SIZE=20 --HEADER_OFFSET=-0.35c -R${area2} -JX${ratio} -B/a50f10:"N@-d@- [mosquitoes human@+-1@+]":E -O -K >> out.ps
psxy datN -R${area2} -m -Wthickest,green -JX${ratio} -O -K >> out.ps
psxy datRR -R${area1} -Sb0.05c -m -Gblack -JX${ratio} -O -K >> out.ps

echo "0 0 14 90 Helvetica-Bold CM EIR@-d@-*30 [bites day@+-1@+]" > dat1
pstext dat1 -JX${ratio} -R-5/5/-5/5 -Gred -Y4.5 -X-13.6 -O -K >> out.ps

echo "0 0 14 90 Helvetica-Bold CM HBR@-d@- [bites day@+-1@+]" > dat1
pstext dat1 -JX${ratio} -R-5/5/-5/5 -Groyalblue -Y-9.0 -O >> out.ps



############################################

convert out.ps -rotate 90 -background white -flatten -trim out.png
mv out.png ${statken}_lmm_daily_${yyyy}.png
mv out.ps ${statken}_lmm_daily_${yyyy}.ps
#gv out.ps

 yyyy=`expr $yyyy + 1`
done

exit